### ISSUE TITLE
feature: submit to official repo

### ISSUE THREAD

**Issue by philips** [philips/supernote-obsidian-plugin#15]
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/philips/obsidian-plugin-supernote

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [xd] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

**Comment by philips** [comment]
submitted https://github.com/obsidianmd/obsidian-releases/pull/3314

**Comment by sigrunixia** [comment]
Congrats for passing through review! Welcome to the community store.

**Comment by philips** [comment]
Thank you @sigrunixia

**Comment by philips** [comment]
Now available in the community store!
