### ISSUE TITLE
bug: pages are out of order

### ISSUE THREAD

**Issue by taisau** [philips/supernote-obsidian-plugin#21]
The pages as shown in Obsidian are in a different order than on the Supernote.

**Comment by philips** [comment]
Huh! Can you attach an example note?

**Comment by taisau** [comment]
I see what is happening now that I created a new blank 1o page note: 
The plugin sorts the pages alpabetically, but Supernote sorts them numerically.
So in Supernote the sequence is 1 2 3 4 5 6 7 8 9 10,
but in obsidian The are 1 10 2 3 4 5 6 7 8 9
** I get valuable daily use from this plugin, btw!**
![2024-05-09_09-08-55](https://github.com/philips/supernote-obsidian-plugin/assets/13009459/9f47d10d-887d-4912-8041-b2a42e9bc634)

**Comment by philips** [comment]
This will be fixed in the next release. Thanks for the report!
