### ISSUE TITLE
Question: Merge Obsidian Notes & Supernote pages?

### ISSUE THREAD

**Issue by erenoglu** [philips/supernote-obsidian-plugin#36]
I started to use Obsidian and have a Supernote nomad as well. I have the same folder structure on both, and same named notes on both. for example, in Obsidian, I have Folder-1/note1.md  and in Supernote I have Folder-1/note1.note

During meetings, I find myself typing on my PC to Obsidian if I have access to separate monitor to host Obsidian, while looking at meeting screens on other monitor.  But if I have only one monitor (ie laptop while in travel), I use my Supernote.

So now I have two notes on the same subject, one hosted in Obsidian and other in Supernote, having data from different timesets. ie I might have taken note today on note1 and tomorrow using Supernote for same note1.  Using your plugin, I can look at both, that is good, I can also copy OCRd text or pictures from supernote note file to Obsidian. But this is very manual process and I did not find the discipline to do it yet. I find myself going back and forth between the two and try to remember which note is newer.

Is there any chance, that the supernote OCRed text notes are mapped between & merged into the Obsidian notes automaticaly on sync based on timestamps?  for example, if I type somethign in my Obsidian, it goes into Supernote note file as text, so when I open my Supernote I can see that text, and if I continue writing on my Supernote on same page, it appears on Obsidian same note when synced, as OCRed text (no pictures needed even if OCR is bad).

 I know, pretty difficult to do with conflicts etc. just wondered if there's a more automated way to merge both using timestamps.

**Comment by philips** [comment]
I don't know how I would approach this feature. And, personally, it isn't something I have a desire to work on. So, I am going to close the issue. If you come up with a good solution I would be interested to see it though!
