### ISSUE TITLE
Supernote A6X2 requires port 8089 for screen mirroring

### ISSUE THREAD

**Issue by malleVF** [philips/supernote-obsidian-plugin#42]
It would be great if the port number could be added to the settings. 
Currently, port 8080 is hardcoded in the script for the connection. For A6X2 connection failed for that reason.

**Comment by philips** [comment]
Hrm, are you certain? On my A5X 8089 is for "Browse & Access" and 8080 is for "Screen Mirroring". Can you please confirm what the Browse and Access port is then?

**Comment by malleVF** [comment]
You are right. Today I got aware about the two different features.

I apologize for my superficial assertion that led to the ticket.
